Task1
Waltans/naumen-course-task pull request #2
Opened 2024-10-25 18:46 UTC by totheskysx10

2024-10-25 18:57 UTC, Waltans commented
Основные обсуждения/комметарии были в этом [мр](https://github.com/Waltans/naumen-course-task/pull/1)

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +}
В конце файлов лучше добавлять newLine

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size()) {
Не все условия проверены, а введут число меньше 0 к примеру?

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size()) {
Тоже самое

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        return "ok";
Давай вынесем в константу как корректный ответ валидации параметров

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +     * Создаёт сообщение об ошибке не найденного пароля
Не тот коммент :)

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +        return String.format("Сгенерирован пароль: %s", password);
Как предложение, можно добавить ``` в начало и конец пароля чтобы его можно было удобно копировать

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +     * Создаёт сообщение об удалении пароля
Тоже не тот коммент

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public void createUserPassword(String password, String description, long userTelegramId) {
Транзакция

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public void updatePassword(String uuid, String description, String password) {
Тоже транзакция

2024-10-28 15:48 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public List<UserPassword> getUserPasswords(long userTelegramId) {
Транзакция на чтение

2024-10-31 16:12 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size()) {
добавил проверку условия отрицательного значения

2024-10-31 16:12 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size()) {
тоже поправил

2024-10-31 16:12 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        return "ok";
ага, вынес)

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +     * Создаёт сообщение об ошибке не найденного пароля
уже уставший был😅
поправил

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +        return String.format("Сгенерирован пароль: %s", password);
пробовал так сделать, почему-то не работает

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +     * Создаёт сообщение об удалении пароля
тоже поправил

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public void createUserPassword(String password, String description, long userTelegramId) {
сделал

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public void updatePassword(String uuid, String description, String password) {
сделал

2024-10-31 16:13 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    public List<UserPassword> getUserPasswords(long userTelegramId) {
сделал

2024-10-31 16:17 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +        return String.format("Сгенерирован пароль: %s", password);
Понял

2024-10-31 16:18 UTC, Waltans commented
Все ок!

2024-11-01 10:47 UTC, Waltans approved these changes
ok!

2024-11-03 10:33 UTC, YaEtoTui commented on src/main/resources/application.properties
> +
Зачем два application. Выберите один. Я как понял этот вообще не используется

2024-11-03 10:36 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +    private static final Logger log = LoggerFactory.getLogger(BotInitialize.class);
Никаких static. Только примитивные константы

2024-11-03 10:36 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
JavaDoc нет. Вы реализовывали, вы и пишите

2024-11-03 10:37 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +public class BotService extends TelegramLongPollingBot {
JavaDoc нет. Уже второй класс...

2024-11-03 10:38 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +import naumenproject.naumenproject.service.MessageService;
не нужные импорты убираем

2024-11-03 10:38 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +    private final Logger log = LoggerFactory.getLogger(BotService.class);
логер не используется -> убирать. И смотрите тут static нет :)

2024-11-03 10:40 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +import java.util.ArrayList;
не нужные импорты

2024-11-03 10:44 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +public interface UserPasswordRepository extends JpaRepository<UserPassword, Long>  {
Ребят, выделяйте код и горячие клавиши Ctrl + Alt + L. Не удобно читать

2024-11-03 10:48 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
может сюда логер?

2024-11-03 10:50 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +     * Поулчает список паролей пользователя
Получает*

2024-11-03 10:51 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Почему тут нет проверки на число строки. Я смотрю выше что проверяете. А тут вы уверены, что ошибку не кинет?

2024-11-03 10:52 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
тут такой же вопрос, что и поводу строки выше

2024-11-03 10:55 UTC, YaEtoTui commented on pom.xml
> +    <dependencyManagement>
У вас проект модульный? Или планируется?

2024-11-03 10:56 UTC, YaEtoTui commented on pom.xml
> +        <spring.boot.version>3.3.4</spring.boot.version>
<url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

Данный момент, я не понимаю что это) Никогда не видел)

Но спрошу: без этого никак?)

2024-11-03 10:56 UTC, YaEtoTui commented on pom.xml
> +        <spring.boot.version>3.3.4</spring.boot.version>
<url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

2024-11-03 10:57 UTC, YaEtoTui commented on pom.xml
> +        <spring.boot.version>3.3.4</spring.boot.version>
![изображение](https://github.com/user-attachments/assets/793256fc-b166-4791-a4b7-712d47b5c90d)

2024-11-03 11:00 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +public class BotService extends TelegramLongPollingBot {
Мне кажется или BotService - это не конфиг)

2024-11-03 11:02 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int complexity = Integer.parseInt(splitCommand[2]);
и тут тоже уверены что int ?

2024-11-03 11:08 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Напомню есть требования по поводу static. Я думаю понятно что нужно делать

2024-11-03 11:09 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate
Добавьте, что если корректно все задано

2024-11-03 11:10 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /del
Мне кажется надо расписать(в каком случае и т.д.) -> при правильном вводе или нет

2024-11-03 11:11 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> + * ����� ��������� ������ ��� CommandService
Кодинг поправьте

2024-11-03 11:11 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> + * ����� ��������� ������ ��� CommandService
![Uploading изображение.png…]()

2024-11-03 11:12 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> +import org.mockito.MockitoAnnotations;
не нужные импорты убираем

2024-11-03 11:13 UTC, YaEtoTui commented
Может лучше тесты в package service перетащить?

2024-11-03 11:15 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +    void testGeneratePassword_Level2() {
Хм, данный тест то успешно проходит то нет. Посмотрите как лучше проверять

2024-11-03 11:15 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +    void testGeneratePassword_Level2() {
Походу тут во всех из-за генерации. Мне кажется если тест не проходит стабильно, значит надо тесты продумать

2024-11-03 11:18 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +     * Тест проверки существования пользователя по Telegram ID
Дописать, что данный user есть

2024-11-03 11:59 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Не понятно о чем вы говорите, есть метод validateCommand, который обрабатывает поступающие команды и там же происходит валидация

2024-11-03 11:59 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Ответил выше

2024-11-03 12:01 UTC, Waltans commented on pom.xml
> +    <dependencyManagement>
Насколько я понимаю, что это требования Вячеслава по оформлению pom файлов, а также для будущего расширения. Ничего плохого не будет, если оставить так, а будет даже лучше :)

2024-11-03 12:04 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int complexity = Integer.parseInt(splitCommand[2]);
отвечал выше

2024-11-03 12:07 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
От того, что я уберу статик из импорта методы не перестанут быть статическими, насколько целесообразно?

2024-11-04 10:00 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
вывода стектрейса будет достаточно

2024-11-04 10:00 UTC, Waltans commented on pom.xml
> +        <spring.boot.version>3.3.4</spring.boot.version>
Тут планировались вписаться методанные проекта, но не вписались, уберу

2024-11-04 12:14 UTC, Waltans commented on src/main/resources/application.properties
> +
fix

2024-11-04 12:14 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +    private static final Logger log = LoggerFactory.getLogger(BotInitialize.class);
Вообще статик в случае логгера кажется уместным, но если таковы требования, то исправлю

2024-11-04 12:14 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
fix

2024-11-04 12:14 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +public class BotService extends TelegramLongPollingBot {
fix

2024-11-04 12:15 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +import naumenproject.naumenproject.service.MessageService;
fix

2024-11-04 12:15 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +    private final Logger log = LoggerFactory.getLogger(BotService.class);
убрал логгер,

2024-11-04 12:15 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +import java.util.ArrayList;
fix

2024-11-04 12:15 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +public interface UserPasswordRepository extends JpaRepository<UserPassword, Long>  {
fix

2024-11-04 12:15 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +     * Поулчает список паролей пользователя
fix

2024-11-04 12:16 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +public class BotService extends TelegramLongPollingBot {
fix

2024-11-04 12:16 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate
ok

2024-11-04 12:19 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> + * ����� ��������� ������ ��� CommandService
fix

2024-11-04 12:19 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> +import org.mockito.MockitoAnnotations;
fix

2024-11-04 12:22 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +    void testGeneratePassword_Level2() {
Если тест проходит нестабильно, то, кажется, что стоит обратить на метод, который он тестирует :)) В нем была ошибка

2024-11-04 12:22 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +     * Тест проверки существования пользователя по Telegram ID
fix

2024-11-04 12:28 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /del
прописал

2024-11-04 15:58 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +    private static final Logger log = LoggerFactory.getLogger(BotInitialize.class);
У вас log даже так в одном классе static, в другом нет -> вы сейчас противоречите самому себе. 
Если считали уместным, почему я при прошлой проверки замечал выше картину (моя строка повыше).

И да, таковы требования)

2024-11-04 16:01 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> + * Компонент по инициализации бота
Кстати а почему тогда если это компонент, он находится в package "configuration"?

2024-11-04 16:05 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
Принято

2024-11-04 16:06 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Не обратил внимание, спасибо) Принято

2024-11-04 16:06 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Я не увидел проверки validateCommand()

2024-11-04 16:10 UTC, YaEtoTui commented on pom.xml
> +    <dependencyManagement>
Я вас понял. Вопросов нет у меня

2024-11-04 16:13 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +    private static final Logger log = LoggerFactory.getLogger(BotInitialize.class);
Я убрал статик в коммите фикса, просто было интересно)

2024-11-04 16:16 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
На столько, что у вас требование такое есть, где static может быть у примитивных констант.

2024-11-04 16:18 UTC, YaEtoTui commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +    void testGeneratePassword_Level2() {
Тоже верное суждение

2024-11-04 16:20 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +    private static final Logger log = LoggerFactory.getLogger(BotInitialize.class);
Я заметил)

2024-11-04 16:20 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
```
 return switch (command) {
                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
                case "/del" -> isNumber(splitCommand[1]);
                case "/edit" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]) && isNumber(splitCommand[3]);
                default -> true;
            };
```

```
   /**
     * Проверяет, является ли строка числом
     * @param string строка
     * @return true, если строка состоит из числа
     */
    private boolean isNumber(String string) {
        try {
            Integer.parseInt(string);
        } catch (NumberFormatException e) {
            return false;
        }

        return true;
    }
```

метод isNumber в случае с неверным значением отдает false и возвращается ответ, что сообщение пришло с ошибкой

2024-11-04 16:23 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private boolean matchPassword(int complexity, String password){
JavaDoc.

2024-11-04 16:23 UTC, YaEtoTui commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private StringBuilder generatePassword(int length, String chars) {
JavaDoc

2024-11-04 16:25 UTC, YaEtoTui commented
1-ое задание принято

2024-11-04 16:26 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> + * Компонент по инициализации бота
Цель компонента - регистрация бота в контексте, что больше похоже на конфигурацию, так как не несет какой-то бизнес-логики

2024-11-04 16:44 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private boolean matchPassword(int complexity, String password){
Добавил

2024-11-04 16:44 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private StringBuilder generatePassword(int length, String chars) {
Добавил

2024-11-07 20:45 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
> От того, что я уберу статик из импорта методы не перестанут быть статическими

Самое время закрыть пробелы в знаниях и начать понимать разницу между статическим импортом и статическим методом. Что каждый из них значит?

2024-11-07 20:55 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
> вывода стектрейса будет достаточно

Достаточно для чего? Или для кого? Если для того, чтобы его никто никогда не увидел, то конечно....)))

А вы точно знаете для чего используется логгер? Поделитесь вашим представлением

А знаете куда выведется результат `e.printStackTrace();`?

> может сюда логер?

В общем замечание требует исправления. Притом надо обязательно написать **человекочитаемое** сообщение об ошибке и не забыть вывести стек

2024-11-08 04:42 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
> Достаточно для чего? Или для кого? Если для того, чтобы его никто никогда не увидел, то конечно....)))

Достаточно для нас, логгер в **нашем случае** выводит сообщение только в консоль (нам этого вполне достаточно на данном этапе), что и так делает это сообщение  "чтобы его никто никогда не увидел", но мы поняли о чем вы говорите

> А вы точно знаете для чего используется логгер? Поделитесь вашим представлением

Конечно понимаю, используется для журналирования событий.

> А знаете куда выведется результат e.printStackTrace();?

Локально в консоль

> Раз уж решили использовать логгер, то используйте его везде.

С этим согласен, поправлю.

2024-11-08 07:07 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
> Самое время закрыть пробелы в знаниях и начать понимать разницу между статическим импортом и статическим методом. Что каждый из них значит?

Убрал static из импортов (соответствуем требованиям)

2024-11-10 17:06 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
точно поняли?

Вообще-то логгер в основном используется для вывода в файл (или несколько файлов).

2024-11-10 17:07 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Нет ответа на вопрос!

2024-11-10 17:09 UTC, vpyzhyanov commented
![image](https://github.com/user-attachments/assets/859d5c8f-89c9-41e5-9bc8-1adf418f89d0)

В итоговом пулл реквесте никаких ваших личных обсуждений быть не должно. Тут уже должно быть всё готово.

2024-11-10 19:36 UTC, vpyzhyanov requested changes
Принимаю вас в адепты тёмной стороны) Может лучше на светлую? Там всё проще и понятнее

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +public class BotService extends TelegramLongPollingBot {
Нарушение наследования. BotService должен являться телеграмм ботом, но

1. У него нет слова Telegram
2. Он не бот, а сервис для работы с ботом

В итоге от предка ничего не осталось, наследование разорвано.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +    private static final Logger log = LoggerFactory.getLogger(BotService.class);
static запрещён!

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +    @Value("${bot.name}")
использовать Inject через поля - очень плохая практика. Используйте через конструктор, тем более вы уже это делаете. А смешивать разные варианты - это ещё более дурной тон

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
добро пожаловать на тёмную сторону. Посмотрите скриншот и постарайтесь ответить на какую именно

![image](https://github.com/user-attachments/assets/3c2dcd81-24d9-4546-b780-23095533f887)

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
Чтобы получилось ООП, у вас должны методы называться в соответствии с тем, что они делают. Тут это не так.

- Метод называется "проверить", значит он ничего не возвращает, но он почему-то возвращает, да ещё и boolean (как до этого можно догадаться?!)
- Если метод возвращает boolean, то он должен задавать вопрос на который есть только 2 ответа: да или нет.
- Метод почему-то связан с телеграммом (`ByTelegramId`), хотя никакой связи с телеграммом у него нет и быть не может

Подходящее название `existsUser` или `isUserExests`. Даже `chatId` можно не писать в названии, т.к. это будет дублирование имени параметра.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
результат работы userService больше тут нигде не используется. Почему тогда он именно здесь?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +package naumenproject.naumenproject.service;
так пакеты никто не называет.

1. Пакеты не должны дублироваться. Не должен вложенный наследник копировать имя родителя
2. Слова принято разделять точками. Надо всячески стараться использовать одно слово.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate, при валидных значениях
опечатка

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.when(messageService.createMessageWithPassword("generatedPassword")).thenReturn("Сгенерирован пароль: generatedPassword");
очень подозрительно.... чем занимается этот сервис?

Этот метод используется ровно 1 раз, возникает веский вопрос о его существовании и смысле. Ничего фантастического или сложного он не делает. Просто однострочный метод

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +public class MessageService {
чем занимается этот сервис? Какова его цель?

Добро пожаловать на тёмную сторону, вы создали класс без цели к существованию. Это всё равно, что создать целый класс просто для того, чтобы делать инкремент, хотя можно сделать просто `i++`. Так же и тут, создать строку можно очень легко там где она нужна. Не нужно для этого классы и тем более спринговые сервисы.

- Все методы, кроме одного вызываются один раз
- Во многих методах даже нет ни единого действия, просто строка.
- Похоже вся цель этого класса добавить сложности к написанию теста, а ещё сделать все условия, чтобы тест ничего не тестировал. Ведь реальные сообщения никто не тестирует.
- Оказывается вы их тестируете. Но в этом столько же смысла, сколько тестировать сервис инкремента для чисел. 

Для этих целей надо использовать **константы** и не мучаться. Не надо из элементарных операций делать сложные сервисы.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +    private final EncodeService encodeService;
это поле очень неожиданно в таком "сервисе". Очень интересно что оно тут делает?

P.S. добро пожаловать на тёмную сторону, вы перегрузили класс ответственностью.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +            String password = encodeService.decryptData(userPasswords.get(i).getPassword());
> это поле очень неожиданно в таком "сервисе". Очень интересно что оно тут делает?
> 
> P.S. добро пожаловать на тёмную сторону, вы перегрузили класс ответственностью.

Оказывается тут ещё одна тёмная сторона. Почему-то MessageService украл работу у обработки конкретной команды. Добро пожаловать в коллективную безответственность.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).generatePasswordWithComplexity(12, 3);
лишняя строчка. Как думаете почему?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageWithPassword("generatedPassword");
лишняя строчка. Как думаете почему?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageLengthError();
весь класс пронизан лишними проверками

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate, если некорректно задана длина (выше)
везде одинаковая опечатка

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        String command = "/generate 4 3";
не надо было выносить в переменную. Это снижает читаемость в данном случае

И везде в этом классе

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).deletePassword(passUuid);
похоже это единственная реально нужная проверка

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.when(messageService.createMessageLengthError()).thenReturn("Длина пароля должна быть от 8 до 128 символов!");
хотя бы на этом этапе надо было задуматься и сказать "Ну зачем мы делали этот сервис, если он нам доставляет столько трудностей и проблем?!"

Ну либо у вас бесконечное количество свободного времени и вы можете себе позволить его тратить на то, что не приносит пользы.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> +        ReflectionTestUtils.setField(encodeService, "secretKey", TEST_KEY);
хмм....магия вне Хогвартса значит. Вообще-то магию надо применять там где она реально необходима, а не в мире маглов. Или в азкабан захотели?

А теперь весело всё это убираем и делаем нормальный inject через конструктор и больше себе проблем не придумываем =)

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/MessageServiceTest.java
> +class MessageServiceTest {
удалить вместе с "сервисом"

Кстати, под словом "сервис" обычно все подразумевают класс, который работает с какими-то объектами, он инкапсулирует логику по их обработке и/или хранению. Один из важных отличительных признаков сервиса - он имеет состояние либо работает с внешним хранилищем, которое это состояние хранит.

В этом смысле MessageService - не сервис вовсе. Он не имеет никакого состояния, да и никакие объекты не обрабатывает.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +        Mockito.verify(userPasswordRepository, Mockito.times(1)).save(ArgumentMatchers.any(UserPassword.class));
прошу не увлекаться однострочным программированием

2024-11-10 19:36 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +        Mockito.verify(userRepository, Mockito.times(1)).findByTelegramId(telegramId);
везде лишние проверки. Почему они лишние?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> + * Компонент по инициализации бота
Да, но и конфигурации в нём никакой нет. Нет ни одной настройки

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
1. Просто читаем название: "Инициализация бота". А вы не перепутали имя пакета с именем класса? Обычно класс называют в соответствии с его ответственностью. Как минимум `BotInitializer`
2. Отсутствие инкапсуляции. Бот сам в состоянии себя запустить, без посторонней помощи.
3. Отсутствие инкапсуляции: к боту может кто угодно обратиться, хотя не должен никто. Его стоит вынести в отдельный пакет и максимально закрыть видимость.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +            e.printStackTrace();
на паре я рассказал как делать правильно

А ещё вопрос: вы точно уверены, что хотите продолжить выполнение программы если бот не запустился? Разве вы не телеграмм бота пишете?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/model/User.java
> +        return telegramId == user.telegramId && Objects.equals(uuid, user.uuid) && Objects.equals(username, user.username) && Objects.equals(userPasswords, user.userPasswords);
станно, ведь мы это уже проходили.... вы хотите сказать, что стоит поменять имя пользователя или добавить любой пароль, то пользователь станет другим?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +public interface UserPasswordRepository extends JpaRepository<UserPassword, Long> {
где JavaDoc?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +    List<UserPassword> findByUserTelegramId(long userTelegramId);
где JavaDoc у всех методов?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
где JavaDoc?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +    private final Map<String, List<Integer>> commandsAndNumberOfParams = Map.of (
пожалуйста, будьте добры, хотя бы в следующей задаче разбить команды на отдельные классы. Не надо засиживаться на тёмной стороне

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String response = "Введена некорректная команда! Справка: /help";
это неожиданно. Только начали парсить команду и вдруг сразу ошибка. Прошу это убрать, это вносит неочевидность. Обработка ошибок должна быть иной

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
добро пожаловать в коллективную безответственность. Как думаете почему?

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +    private boolean validateCommand(String[] splitCommand) {
слово `validate` говорит о том, что метод ничего не возвращает, а в случае ошибки кидает исключение. У вас не так. Если не так, то напишите более подходящее название. Например `isValidCommand`

И далее везде то же самое.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
ой ой ой, не надо так делать. Надёжность этого метода стремится к нулю. Уж в этом случае можно кинуть исключение.

А лучше не исключение, т.к. метод в этом же классе, а разбить проверку на 2 и проверить их отдельно, возвращая boolean.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        return messageService.createMessageWithPassword(password);
вот тут чётко видно, что смысла в этот "сервисе" нет.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        int passwordId = Integer.parseInt(splitCommand[1]);
Добро пожаловать коллективную безоствественность

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String uuid = userPasswords.get(passwordId - 1).getUuid();
Как `-1`? Откуда? Зачем? Почему?

Магические числа какие-то

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String description = userPasswords.get(passwordId - 1).getDescription();
И ещё раз? Дублирование использования магических чисел

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
1. Дублирование кода
2. Дублирование ошибки

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String uuid = userPasswords.get(passwordId - 1).getUuid();
опять магические числа

И ещё кое что куда более страшное и тёмное. Вы ввели всех в заблуждение, назвали переменную `passwordId`, хотя это вообще не идентификатор, а это **индекс**

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size() || passwordId <= 0) {
то есть вы поднимаете **ВСЕ** объекты, просто для того, чтобы проверить индекс? Производительность будет мягко говоря не рада.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (splitCommand.length == 5) {
магические числа надо выносить в константы с понятными именами

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +    private final String ALGORITHM = "AES";
static

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
думаю вы поняли что тут надо написать.

А вообще тут проглатывать ошибку в корне неверно, на этом уровне её невозможно корректно обработать. Выбросите её дальше.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
всё то же самое

И никаких null!

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private final SecureRandom RANDOM = new SecureRandom();
это не константа, что бы её так называть

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +     * @param userTelegramId ID пользователя в telegram
даже в JavaDoc зашили искусственную связь с телеграаммом, которой на самом деле нет.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    @Transactional
Похоже вы пока не знаете что такое транзакционность. На одном из занятий я расскажу об этом.

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +        userPassword.setPassword(encodedPassword);
и зачем мучаться? Создайте нужный конструктор

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +        user.setTelegramId(telegramId);
и зачем мучаться? Создайте нужный конструктор

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            throw new IllegalArgumentException("Пароль не найден!");
Нигде не обрабатываете это исключение. Оно должно быть **проверяемым**!

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            default -> throw new IllegalStateException("Unexpected value: " + complexity);
Пожалуйста, внимательнее читайте JavaDoc. И больше не используйте неуместные типы исключений.

![image](https://github.com/user-attachments/assets/3bddae6e-c543-4c8d-80b1-b3d1a9485309)

Даже название говорит о том, что оно неуместно

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            default -> throw new IllegalStateException("Unexpected value: " + complexity);
то же самое

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
Ого, вот этого я точно не ожидал. Вы перепутали реализацию с тестами. Обычно совершают другую ошибку, наоборот в тестах делают реализацию, а вы в реализации написали тест. Убираем

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +            throw new IllegalArgumentException(String.format("Пользователь с id %s не найден", telegramId));
это должно быть проверяемым исключением

2024-11-10 19:36 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +    public boolean checkUserExistsByTelegramId(long telegramId) {
1. имя некорректно
2. Опять эта лишняя связь с телеграаммом, которой на самом деле нет.

2024-11-10 19:36 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>jaxb-api</artifactId>
будьте добры, покажите мне место в коде, где вы используете эту библиотеку

2024-11-10 19:36 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>spring-boot-starter-web</artifactId>
будьте добры, покажите мне место в коде, где вы используете эту библиотеку

2024-11-10 19:36 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>spring-boot-starter-validation</artifactId>
будьте добры, покажите мне место в коде, где вы используете эту библиотеку

2024-11-10 19:36 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>spring-boot-starter-data-rest</artifactId>
будьте добры, покажите мне место в коде, где вы используете эту библиотеку

2024-11-10 19:55 UTC, totheskysx10 commented on pom.xml
> +                <artifactId>spring-boot-starter-web</artifactId>
видимо при инициализации Spring-проекта подтянулась сама. убрал

2024-11-10 19:56 UTC, totheskysx10 commented on pom.xml
> +                <artifactId>spring-boot-starter-validation</artifactId>
ответил выше)

2024-11-10 19:56 UTC, totheskysx10 commented on pom.xml
> +                <artifactId>spring-boot-starter-data-rest</artifactId>
ответил выше)

2024-11-10 19:58 UTC, totheskysx10 commented on pom.xml
> +                <artifactId>jaxb-api</artifactId>
явно нигде не используется, но без неё падает BeanCreationException, ошибка создания бина entityManagerFactory - приложение не стартует

2024-11-10 19:59 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +public class BotService extends TelegramLongPollingBot {
поменял название

2024-11-10 20:00 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +    private static final Logger log = LoggerFactory.getLogger(BotService.class);
убрал

2024-11-10 20:03 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +    @Value("${bot.name}")
поправил

2024-11-10 20:04 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
переименовал

2024-11-10 20:05 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +package naumenproject.naumenproject.service;
переименовал

2024-11-10 20:07 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate, при валидных значениях
поправил

2024-11-10 20:13 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).generatePasswordWithComplexity(12, 3);
думаю, потому что тестируем CommandService, а строчка проверяет работу PasswordService. убрал её

2024-11-10 20:13 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageWithPassword("generatedPassword");
аналогично

2024-11-10 20:15 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageLengthError();
убрал их

2024-11-10 20:16 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +     * Тест комады /generate, если некорректно задана длина (выше)
поправил

2024-11-10 20:19 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        String command = "/generate 4 3";
поправил

2024-11-10 20:24 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/EncodeServiceTest.java
> +        ReflectionTestUtils.setField(encodeService, "secretKey", TEST_KEY);
сделал

2024-11-10 20:29 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).deletePassword(passUuid);
понял

2024-11-10 20:29 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/PasswordServiceTest.java
> +        Mockito.verify(userPasswordRepository, Mockito.times(1)).save(ArgumentMatchers.any(UserPassword.class));
поправил

2024-11-10 20:30 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +        Mockito.verify(userRepository, Mockito.times(1)).findByTelegramId(telegramId);
как и в случае выше - мы проверяем уже итоговый результат работы тестируемого метода, а не то, как он получен. убрал их

2024-11-10 20:34 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
поменял название и настройки видимости

2024-11-10 20:34 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +    public boolean checkUserExistsByTelegramId(long telegramId) {
поправил

2024-11-10 20:36 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +            e.printStackTrace();
да, согласен, логичнее будет завершать программу. поправил

2024-11-10 20:38 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/model/User.java
> +        return telegramId == user.telegramId && Objects.equals(uuid, user.uuid) && Objects.equals(username, user.username) && Objects.equals(userPasswords, user.userPasswords);
нет, пользователь останется такой же. поправил

2024-11-10 20:42 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +public interface UserPasswordRepository extends JpaRepository<UserPassword, Long> {
дописал

2024-11-10 20:43 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/repository/UserPasswordRepository.java
> +    List<UserPassword> findByUserTelegramId(long userTelegramId);
дописал

2024-11-10 20:43 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
дописал

2024-11-10 20:43 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +    private final Map<String, List<Integer>> commandsAndNumberOfParams = Map.of (
хорошо

2024-11-10 20:44 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +    private final String ALGORITHM = "AES";
добавил

2024-11-10 20:49 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String response = "Введена некорректная команда! Справка: /help";
поправил

2024-11-10 20:50 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +    private boolean validateCommand(String[] splitCommand) {
поправил

2024-11-10 21:14 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.when(messageService.createMessageWithPassword("generatedPassword")).thenReturn("Сгенерирован пароль: generatedPassword");
сервис создаёт сообщения для ответов. но согласен, что используется лишь один раз, и содержание не тянет на отдельный сервис. вынес в константы, а класс удалил)

2024-11-10 21:14 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +public class MessageService {
ответил выше

2024-11-10 21:15 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +            String password = encodeService.decryptData(userPasswords.get(i).getPassword());
перенёс в CommandService, чтобы использовать при обработке команды

2024-11-10 21:17 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/MessageService.java
> +    private final EncodeService encodeService;
планировалось, что прилетят шифрованные пароли, а дешифруются для ответа пользователю уже при создании сообщения. но так как класс не нужен, теперь это обрабатывается непосредственно при обработке команды

2024-11-10 21:17 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.when(messageService.createMessageLengthError()).thenReturn("Длина пароля должна быть от 8 до 128 символов!");
да, понял ошибку

2024-11-10 21:18 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/MessageServiceTest.java
> +class MessageServiceTest {
удалил, переделал с исп. констант

2024-11-10 21:18 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        return messageService.createMessageWithPassword(password);
да, уже понял)

2024-11-10 21:20 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String uuid = userPasswords.get(passwordId - 1).getUuid();
потому что в списках в Java счёт идёт с нуля, а пользователю мы выводим список, который начинается с единицы, т.е. когда пользователь выбирает пароль, нужно убавить единицу от выбранного им индекса. Но согласен с комментарием ниже про индекс, поменял название

2024-11-10 21:20 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String uuid = userPasswords.get(passwordId - 1).getUuid();
ответил выше

2024-11-10 21:21 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String description = userPasswords.get(passwordId - 1).getDescription();
ответил выше

2024-11-10 21:25 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size() || passwordId <= 0) {
моё видение такое - нужно как минимум получить список с паролями пользователя, чтобы проверить индекс, что здесь и делается)

2024-11-10 21:27 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (splitCommand.length == 5) {
поправил

2024-11-10 21:35 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    @Transactional
хорошо

2024-11-10 21:35 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +        userPassword.setPassword(encodedPassword);
сделал

2024-11-10 21:35 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +        user.setTelegramId(telegramId);
сделал

2024-11-10 21:37 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +    private final SecureRandom RANDOM = new SecureRandom();
поправил

2024-11-10 21:38 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +     * @param userTelegramId ID пользователя в telegram
поправил

2024-11-10 21:46 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +            throw new IllegalArgumentException(String.format("Пользователь с id %s не найден", telegramId));
поправил

2024-11-10 21:49 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            default -> throw new IllegalStateException("Unexpected value: " + complexity);
поменял на IllegalArgumentException - речь про аргументы метода, так что оно сюда подходит

2024-11-10 21:49 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            default -> throw new IllegalStateException("Unexpected value: " + complexity);
ответил выше

2024-11-10 22:00 UTC, totheskysx10 commented
залил коммит с исправлениями, но исправлено ещё не всё (и ответы даны не на все комментарии). Продолжим немного позже

2024-11-11 15:51 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
А разве это не момент реализации? При создании пароля нам необходимо чтобы пароль соответствовал какому-то из правил, в нашем случае в самом сложном варианте должен содержать символы из всех наборов. Так как пароли генерируются случайным образом мы не можем гарантировать, что он будет содержать все символы из набора поэтому нам необходима такая проверка при генерации

2024-11-11 16:50 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotService.java
> +            e.printStackTrace();
Я же пишу, что в нашем случае

2024-11-11 16:54 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Я честно не понимаю какой ответ вы хотите услышать. Статический импорт используется как shortcut и на паре мы выяснили, что это проблема тут только в том, что используется static (который запрещен по требованиям) и в ухудшении читаемости, с чем я не могу быть полностью согласен, ведь на мой взгляд в тестах уместно использовать, так как все понимают о чем речь

2024-11-11 16:59 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> + * Компонент по инициализации бота
перенесли

2024-11-11 16:59 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Но в целом если несколько статик импортов сделать и там будут какие-н одинаковые методы допустим в разных импортах, есть определенные риски

2024-11-11 17:00 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
исправил

2024-11-11 17:04 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
Метод выполняет проверку параметров, что нарушает принцип единой ответственности.
исправил

2024-11-11 17:04 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
исправил

2024-11-11 17:05 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        String uuid = userPasswords.get(passwordId - 1).getUuid();
вынес переменную в константу и добавил комментарий

2024-11-11 17:05 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
изменил поведение

2024-11-11 17:06 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
так и сделаем

2024-11-11 17:06 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
окей

2024-11-11 17:07 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            throw new IllegalArgumentException("Пароль не найден!");
вы правы

2024-11-11 17:09 UTC, Waltans commented
Уважаемые проверяющие, пожалуйста, закрывайте треды, которые исправлены, а то гит начинает лагать и очень неудобно и непонятно, где уже ответили, а где нет :(

2024-11-13 19:20 UTC, vpyzhyanov commented
> Уважаемые проверяющие, пожалуйста, закрывайте треды, которые исправлены, а то гит начинает лагать и очень неудобно и непонятно, где уже ответили, а где нет :(

Закрывать обсуждения могут только участники проекта (коллабораторы). Мы с Егором ими не являемся. Поэтому даже возможности нет их закрыть, ведь вы сами не разрешили это делать.

2024-11-13 19:30 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Давайте разберём. На просьбу убрать статик у вас было возражение:

> От того, что я уберу статик из импорта методы не перестанут быть статическими, насколько целесообразно?

Причина такого возражения, а главное аргументация, мне совершенно не понятны. Из этого я могу предположить, что вы не различаете как работает слово static в разном контексте (импорты и методы). Отсюда и вопрос:

> Самое время закрыть пробелы в знаниях и начать понимать разницу между статическим импортом и статическим методом. **Что каждый из них значит?**

И небольшой комментарий про это:

> Но в целом если несколько статик импортов сделать и там будут какие-н одинаковые методы допустим в разных импортах, есть определенные риски

Рисков тут никаких нет, код просто не скомпилируется. Проблемы могут начаться тогда когда методы отличаются, Но очень похожи.

2024-11-13 19:42 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +public class BotService extends TelegramLongPollingBot {
Замечание исправлено только на половину. А значит не исправлено!

![image](https://github.com/user-attachments/assets/3fb09d10-77e7-47cb-ab49-0087968dc8d5)

Исправить название, но не исправить описание, всё равно что вставить палку в колесо. А если это уже не сервис, то нужно сделать аннотацию `@Component`

2024-11-13 19:49 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    public TelegramBot(@Value("${bot.token}") String botToken, UserService userService, CommandService commandService, @Value("${bot.name}") String botName) {
1. userService не используется
2. Однострочное программирование - это отстой

2024-11-13 19:49 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
> Посмотрите скриншот и постарайтесь ответить на какую именно

Нет ответа! Ребята, вы сопротивляетесь процессу обучения. Зачем вы это делаете? Если и дальше так будете делать, то я буду просто 0 баллов ставить за ООП и всё. В этом случае даже проще будет, можно будет проверять только базовые требования.

> результат работы userService больше тут нигде не используется. Почему тогда он именно здесь?

Нет ответа

2024-11-13 19:51 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
Теперь этот метод нигде не используется. Так и задумано? Или функционал потерялся?

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/UserService.java
> +    public boolean isUserExists(long telegramId) {
Теперь этот метод нигде не используется. Так и задумано? Или функционал потерялся?

2024-11-13 20:47 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).generatePasswordWithComplexity(12, 3);
ответ неправильный. А особенно неправильно звучит это:

> строчка проверяет работу PasswordService

Это в корне неверно, работа PasswordService вообще никак не проверяется

2024-11-13 20:47 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageWithPassword("generatedPassword");
Да, аналогично, но ответ был неправильный

2024-11-13 20:47 UTC, vpyzhyanov commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +        Mockito.verify(userRepository, Mockito.times(1)).findByTelegramId(telegramId);
вроде и логично, но тут суть куда более банальная и простая. А её вы не назвали. Подумайте ещё.

И иногда бывает очень важно как получен результат. Ну точнее чаще бывают случаи когда должны сделаться какие-то дополнительные действия, которые напрямую не влияют на результат, а на работу программы очень сильно влияют. 

Например сохранение объекта. Вроде проверки все сделали, исключений не возникло и метод вернул true. Но **очень важно** проверить, что вызвался метод сохранения объекта в БД. На результат это не влияет, но на работу очень даже.

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
И как это называется? Выполнили только первый пункт, а остальные **проигнорили**!

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/CommandService.java
> +            return e.getMessage();
1. Потеряли стек
2. Где человекочитаемое сообщение? Если скажете, что внутри самого исключения, то я очень огорчусь. Ведь тогда получится, что вы перепутали бизнес-логику и ошибки. Бизнес-логика не может быть ошибкой и наоборот.
3. (продолжение предыдущего) Не далеко ушли от "Вовки в тридевятом царстве". Сам кинул исключение, сам обработал и всё в одном классе. Тут лучше чуть дублировать код, зато кода будет намного меньше (на самом деле дублирования почти не будет, ведь у вас есть константы)

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
Верно. Команда должна быть самостоятельной, пусть сама проверяет то, чем сама же пользуется.

Почему тогда не исправили?

![image](https://github.com/user-attachments/assets/94fcad36-69a2-4075-b02e-d5dd78fad7e2)

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
странно, выбрали варианты который хуже, очень странно. В чём смысл?

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size() || passwordId <= 0) {
Ну то есть базы данных не изучали? Про count не слышали? Впрочем ладно, мы на курсе не изучаем базы данных

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
стало заметно лучше, но тут есть проблемки:

1. Вы точно понимаете что произойдёт если выбросить RuntimeException? Вы точно этого хотите?
2. Человекочитаемое сообщение должно быть в исключении тоже!
3. Теперь логгирование дублируется. Ну то есть логика должна быть такой: логирование делаем там, где исключение **обрабатывается**. Иначе оно будет логироваться дважды.

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
те же проблемы

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +     * @param userTelegramId ID пользователя в telegram
Исправлено не полностью

![image](https://github.com/user-attachments/assets/1e30c2d2-c82f-48a8-8742-1082c6d457fa)

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            throw new IllegalArgumentException("Пароль не найден!");
Мда.... "вы правы, но исправлять не буду".... проверяемым оно не стало почему-то

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
Если не доверяете своему генератору пароля, то возьмите другой, которому доверяете.

> Поэтому возникла идея проверять пароль на соответствующую сложность

Ключевое слово "проверять". Так что нет, это не момент реализации.

Если так всё время делать (никому не доверять), то вы каждый раз будете проверять идентификатор объекта на валидность после сохранения в БД (формат + уникальность). И вообще в коде будет миллиард проверок.

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
Не исправлено

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +            throw new IllegalArgumentException(String.format("Пользователь с id %s не найден", telegramId));
хорошо. Вот только с проверкой что-то не заладилось. Ошибки глушить - плохая идея.

![image](https://github.com/user-attachments/assets/d0640be2-72bb-4e43-beb9-4824d033140e)

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/PasswordService.java
> +            log.error("Ошибка при создании пароля - не найден пользователь", e);
Ошибки глушить - плохая идея. Никто об этой ситуации не узнает.

2024-11-13 20:47 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +    public boolean checkUserExistsByTelegramId(long telegramId) {
где исправили? Не вижу

![image](https://github.com/user-attachments/assets/e02e6426-4d3e-409e-b5b8-34c608c8e8d2)

2024-11-13 20:54 UTC, vpyzhyanov commented on pom.xml
> +                <artifactId>jaxb-api</artifactId>
Моя "любимая" отмазка)) "без этого не работает". Впрочем ладно, это не критично, пусть будет

2024-11-13 20:55 UTC, vpyzhyanov requested changes
Не на все вопросы я получил ответ. Не все замечания исправлены

2024-11-13 20:59 UTC, vpyzhyanov commented
Оценка за Git: 1 балл из 3. И то только за понятные комментарии

![image](https://github.com/user-attachments/assets/c92ec984-4860-42ad-b8f0-c5e2a82e1d30)

- Активно используются прямые коммиты в ветку задачи без код ревью внутри команды
- Нет использования веток
- Нет использования пулл реквестов (частично есть, но не достаточно)
- Не было командной работы (но тут понятно почему)

2024-11-14 04:20 UTC, Waltans commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Хорошо, понял

2024-11-14 04:24 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
> добро пожаловать на тёмную сторону. Посмотрите скриншот и постарайтесь ответить на какую именно

Сервис взял на себя обязанность, которую не должен был брать, проверять, что пользователь уже существует должен делать userService в соответствующем классе, комментарий это подтверждает

2024-11-14 06:48 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +import static org.junit.jupiter.api.Assertions.assertEquals;
Ответ на вопрос про разницу: статический импорт позволяет обращаться к методу без указания класса. А статический метод - это метод, который принадлежит классу, а не его экземплярам.

2024-11-14 06:52 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(passwordService).generatePasswordWithComplexity(12, 3);
Не совсем корректно выразился. Получается, мы выше мокаем PasswordService и явно указываем ему что возвращать при вызове метода (вернётся "generatedPassword"). И тестируем мы в итоге ComamdService, т.е. неважно какой там пароль, главное чтобы он отправился пользователю корректный сообщением. А саму логику генерации проверяют другие тесты

2024-11-14 06:52 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/CommandServiceTest.java
> +        Mockito.verify(messageService).createMessageWithPassword("generatedPassword");
Ответил выше

2024-11-14 06:55 UTC, totheskysx10 commented on src/test/java/naumenproject/naumenproject/UserServiceTest.java
> +        Mockito.verify(userRepository, Mockito.times(1)).findByTelegramId(telegramId);
С сохранением да, понял. А здесь проверка лишняя, так как мы уже раннее проверяем, какой объект вернулся, и если бы мы не обращались к БД (что и проверяет моя строка), то оттуда вернулось бы null, и тест бы не прошёл

2024-11-14 06:59 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
П. 1 выполнен - название изменено
П. 3 выполнен - изменены настройки видимости, класс перенесен в отдельный пакет
Про п. 2 правда не совсем понимаю, ведь это, насколько я знаю, стандартный код работы Telegram бота

2024-11-14 07:28 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +public class BotService extends TelegramLongPollingBot {
исправил аннотацию и доку

2024-11-14 07:30 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
да, теперь его заменил другой метод - createUserIfUserNotExists. Этот убрал. Здесь заодно хотелось бы задать вопрос - как отслеживать такие потери функционала методов? Ведь Idea показывает, что он используется, хоть и только в тестах. Получается, только каждый раз usages проверять?

2024-11-14 07:36 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
исправил, теперь команда сама это проверяет

2024-11-14 07:45 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (passwordId > userPasswords.size() || passwordId <= 0) {
переделал с исп. count

2024-11-14 07:45 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +     * @param userTelegramId ID пользователя в telegram
теперь полностью убрал связь с тг

2024-11-14 07:46 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +    public boolean checkUserExistsByTelegramId(long telegramId) {
теперь полностью убрал связь с тг

2024-11-14 08:07 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
переделал алгоритм - теперь работает без лишних проверок

2024-11-14 08:11 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            throw new IllegalArgumentException("Пароль не найден!");
сделал проверяемое

2024-11-14 08:16 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    public TelegramBot(@Value("${bot.token}") String botToken, UserService userService, CommandService commandService, @Value("${bot.name}") String botName) {
убрал userService, избавился от одной строки

2024-11-14 09:16 UTC, totheskysx10 commented
пока исправлена лишь часть замечаний - продолжим немного позже

2024-11-14 16:57 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
> Нет ответа! Ребята, вы сопротивляетесь процессу обучения. Зачем вы это делаете? Если и дальше так будете делать, то я буду просто 0 баллов ставить за ООП и всё. В этом случае даже проще будет, можно будет проверять только базовые требования.

Извините, мы не собираемся сопротивляться процессу обучения, мне почему-то показалось что комментария, что я исправил замечание будет достаточно, постараемся впредь отвечать на все вопросы развернуто, аргументируя изменения и, конечно, исправлять все замечания.

2024-11-14 17:24 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
Если я вас правильно понял, то кидать ошибку в этом же классе нет резона, лучше сразу её обработаем, так и сделал

2024-11-14 17:42 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +                case "/generate" -> isNumber(splitCommand[1]) && isNumber(splitCommand[2]);
Опять таки не одна зона ответственности метода поэтому вынес switch в новый метод

2024-11-14 17:45 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
1. Сделал лучше свой Exeption, наследуемый от рантайма и передаю в нем ошибку
2. Напиал комментарий
3. Убрал из этого метода логгирование

2024-11-14 17:47 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
Провел ту же операцию

2024-11-14 18:01 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +            throw new IllegalArgumentException(String.format("Пользователь с id %s не найден", telegramId));
В этом методе выбросим исключение дальше, а там его обработаем

2024-11-14 18:20 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/EncodeService.java
> +            e.printStackTrace();
- рантайм автоматом пробрасывается вверх и не требует обработки (если её не будет до самого верха, поток завершится)
- в нашем случае будет try-catch и логирование

2024-11-14 18:24 UTC, Waltans commented on src/main/java/ru/naumen/service/CommandService.java
> +            return e.getMessage();
Теперь этого нет, как и не было изначально необходимости

2024-11-14 18:25 UTC, Waltans commented on src/main/java/ru/naumen/service/PasswordService.java
> +            log.error("Ошибка при создании пароля - не найден пользователь", e);
ошибка передается дальше и обрабатывается

2024-11-14 18:36 UTC, Waltans commented
> Закрывать обсуждения могут только участники проекта (коллабораторы). Мы с Егором ими не являемся. Поэтому даже возможности нет их закрыть, ведь вы сами не разрешили это делать.

Я кинул вам приглашение в участники, примите, пожалуйста

Вроде бы ответили на все комментарии и все замечания постарались исправить

2024-11-14 18:43 UTC, Waltans commented
> Оценка за Git: 1 балл из 3. И то только за понятные комментарии

С гитом история понятна, будем исправлять в следующем задании

2024-11-14 18:47 UTC, Waltans commented on src/main/java/naumenproject/naumenproject/service/PasswordService.java
> +            case 3 -> password.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()\\-_=+<>?])[a-zA-Z\\d!@#$%^&*()\\-_=+<>?]+$");
Понял проблему и почему этого быть не должно

2024-11-17 15:32 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +                userService.createUser(userId, username);
всё-таки вопросы я задаю не просто так, а чтобы помочь вам чему-то научиться. Ну и увидеть, что вы чему-то научились

2024-11-17 15:35 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
Только в момент изменения архитектуры. Ну то есть когда вы решили переложить ответственность на другой класс, в этот момент надо не забыть снять эту ответственность со старого класса. Автоматически увы это не выйдет. Но если сделать это сразу, то шансов не забыть будет гораздо больше

2024-11-17 15:45 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
А я и не писал замечаний на TelegramLongPollingBot, я их писал на ваш BotInitializer и TelegramBot. В общем тут надо сделать так:

1. Удалить `BotInitializer `совсем (он не нужен)
2. Всё что делает BotInitializer поместить в `TelegramBot`, так бот сам себя запустит. Ответственность тут не перегружается, он же бот, может сам за себя ответить. Да и на другие внешние классы это никак не сказывается, эта логика инкапсулируется внутри и никто про неё знать не обязан.
3. Сделать TelegramBot `package-private`

P.S. очень странно, что BotInitializer находится в пакете `initialize`, ведь он запускает **БОТА**, поэтому логично ему было находится в пакете `bot`. В этом случае с инкапсуляцией дела бы обстояли чуть лучше.

2024-11-17 15:49 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
да, всё правильно. Только не все методы получили правильный нейминг

![image](https://github.com/user-attachments/assets/9770892e-29d7-4051-a642-3f47a9cad222)

лучше их называть `isValid...`

2024-11-17 15:55 UTC, vpyzhyanov commented on src/main/java/naumenproject/naumenproject/service/UserService.java
> +            throw new IllegalArgumentException(String.format("Пользователь с id %s не найден", telegramId));
Вот теперь правильно

2024-11-17 15:58 UTC, vpyzhyanov approved these changes
Задача принята. Как исправите последние небольшие замечания, можете мёрджить.

Процесс обучения прошёл успешно. Оценка за ООП: 5 баллов.

2024-11-17 16:58 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/BotService.java
> +            if (!userService.checkUserExistsByTelegramId(userId)) {
хорошо, понял, спасибо)

2024-11-17 17:18 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/configuration/BotInitialize.java
> +public class BotInitialize {
ага, выполнил все 3 пункта

2024-11-17 17:20 UTC, totheskysx10 commented on src/main/java/naumenproject/naumenproject/service/CommandService.java
> +        if (!paramsValidationResult.equals(VALIDATION_OK)) {
ага, это было сделано во 2 задании - поправил и здесь)

2024-11-17 17:23 UTC, merged