Task2
Waltans/naumen-course-task pull request #6
Opened 2024-11-15 15:21 UTC by Waltans

2024-11-17 13:14 UTC, YaEtoTui commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final int COMMAND_WITHOUT_PARAMS_LENGTH = 1;
Не используете нигде

2024-11-17 13:19 UTC, YaEtoTui commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +     * Клавиатура с выбором сложности
Ребят, методы выполняют какое-то действие. Где оно?
То начиная с этого метода и ниже. Нужно javaDoc хорошо расписывать

2024-11-17 13:21 UTC, YaEtoTui commented on src/main/java/ru/naumen/exception/PasswordNotFoundException.java
> +public class PasswordNotFoundException extends Exception {
Наследование от Exception? Точно от него лучше?

2024-11-17 13:22 UTC, YaEtoTui commented on src/main/java/ru/naumen/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
Наследование от Exception? Точно от него лучше?

2024-11-17 13:23 UTC, YaEtoTui commented on src/main/java/ru/naumen/handler/FindHandler.java
> +import java.util.ArrayList;
импорт не используется

2024-11-17 13:28 UTC, YaEtoTui commented on src/main/java/ru/naumen/service/EncodeService.java
> +import org.slf4j.LoggerFactory;
импорты не используются

2024-11-17 13:29 UTC, YaEtoTui commented on src/test/java/ru/naumen/bot/UserStateCacheTest.java
> + * ����� ��������� ������ UserStateCache
encoding...

2024-11-17 13:29 UTC, YaEtoTui commented on src/test/java/ru/naumen/bot/UserStateCacheTest.java
> + * ����� ��������� ������ UserStateCache
![Uploading изображение.png…]()

2024-11-17 13:39 UTC, YaEtoTui commented
![изображение](https://github.com/user-attachments/assets/c80158bb-1325-4218-b81c-301d5d2ac842)

Сложность в виде чисел плохая практика, как минимум расписывают, вы то знаете, так как пишете его. А вот пользователь может не понять.
И как бы изначально кнопки были другие)

2024-11-17 13:41 UTC, YaEtoTui commented
![изображение](https://github.com/user-attachments/assets/960d70de-0325-4e76-8292-4ffd8d0b93fc)

Поломалась логика

2024-11-17 13:45 UTC, YaEtoTui commented
![изображение](https://github.com/user-attachments/assets/08a4b627-e472-4730-97e1-5e3d74e5f81d)

Не знаю в чем проблема, но пароль некорректно сохраняется :3

2024-11-17 13:47 UTC, YaEtoTui commented
![изображение](https://github.com/user-attachments/assets/4043f156-0942-4024-abf4-a681f928e520)

Нет, все таки это баг. Уже не первый раз, после фразы "введите описание" вот такая каша

2024-11-17 13:47 UTC, YaEtoTui commented
Есть замечания!

2024-11-17 16:03 UTC, Waltans commented
> Сложность в виде чисел плохая практика, как минимум расписывают, вы то знаете, так как пишете его. А вот пользователь может не понять.
> И как бы изначально кнопки были другие)

Фикс по багу влит

2024-11-19 09:16 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final int COMMAND_WITHOUT_PARAMS_LENGTH = 1;
убрал

2024-11-19 09:16 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +     * Клавиатура с выбором сложности
дописал javadoc - теперь описал действие каждой кнопки

2024-11-19 09:17 UTC, totheskysx10 commented on src/main/java/ru/naumen/exception/PasswordNotFoundException.java
> +public class PasswordNotFoundException extends Exception {
исключение должно быть проверяемое, ведь мы ожидаем выброс этого исключения, оно выкидывается не в следствие ошибок нас (разработчиков). + так сделано по замечанию Вячеслава в 1 задаче

2024-11-19 09:17 UTC, totheskysx10 commented on src/main/java/ru/naumen/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
ответил выше)

2024-11-19 09:17 UTC, totheskysx10 commented on src/main/java/ru/naumen/handler/FindHandler.java
> +import java.util.ArrayList;
убрал

2024-11-19 09:17 UTC, totheskysx10 commented on src/main/java/ru/naumen/service/EncodeService.java
> +import org.slf4j.LoggerFactory;
убрал

2024-11-19 09:18 UTC, totheskysx10 commented on src/test/java/ru/naumen/bot/UserStateCacheTest.java
> + * ����� ��������� ������ UserStateCache
исправил

2024-11-19 09:18 UTC, totheskysx10 commented
> Сложность в виде чисел плохая практика, как минимум расписывают, вы то знаете, так как пишете его. А вот пользователь может не понять. И как бы изначально кнопки были другие)

кнопки сделал такие же, как описано в задании - теперь подписи в виде слов

2024-11-24 06:55 UTC, YaEtoTui commented on src/main/java/ru/naumen/exception/PasswordNotFoundException.java
> +public class PasswordNotFoundException extends Exception {
Понял. Вопросов нет)

2024-11-24 07:00 UTC, YaEtoTui commented
Вопросов нет. Баг поправлен.

2-ое задание принято

2024-11-26 18:54 UTC, vpyzhyanov commented
В пулл реквесте конфликты! Прошу их устранить

Почему первая задача не влита во вторую? У меня нет никакого желания писать одни и те же замечания, которые я писал в первой задаче. Вторая задача должна учитывать все исправления из первой.

Буду смотреть задачу только после этих исправлений

2024-11-27 08:32 UTC, totheskysx10 commented
> В пулл реквесте конфликты! Прошу их устранить
> 
> Почему первая задача не влита во вторую? У меня нет никакого желания писать одни и те же замечания, которые я писал в первой задаче. Вторая задача должна учитывать все исправления из первой.
> 
> Буду смотреть задачу только после этих исправлений

Конфликты устранены, первая задача влита во вторую - теперь все изменения учитываются)

2024-11-27 19:04 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/PasswordService.java
> -<<<<<<< HEAD
ого, похоже вы мёрджите через консоль. Ну удачи вам)) Только по настоящему не ленивые программисты между простым и сложным выбирают всегда сложное)

2024-11-27 19:36 UTC, vpyzhyanov requested changes
Ребята, в чём дело? Почему возникают такие сложности, почему не получается соблюсти элементарные требования?

Пока не приведёте код в соответствие требованиям, дальше проверять не буду!

2024-11-27 19:36 UTC, vpyzhyanov commented on pom.xml
> -    </scm>
удивительно, что эти изменения всё ещё здесь. Может это потому, что влили не main, а task1?

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Command.java
> +public class Command {
уместнее было использовать enum. Тогда и имя в единственном числе будет оправдано. А то сейчас описание не соответствует имени.

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final Map<String, List<Integer>> commandsAndNumberOfParams = Map.of(
Ребята, в чём дело? Разве так сложно соблюсти элементарные требования?

Если бы делали куда более подходящую структуру для этого класса (enum), то создавать такие поля бы не потребовалось.

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final Map<String, String> commandKeyMapping = Map.of(
ещё и всё публично. Инкапсуляция - давай до свидания. По сути весь этот класс - просто свалка статических полей, связанных с командой. Не надо так. Команда должна быть самодостаточна и должна инкапсулировать все необходимые данные внутри себя. Пока вижу только процедурное программирование

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String WELCOME_MESSAGE = "Здравствуйте. Я бот, который поможет Вам генерировать и управлять паролями.\n\n" +
самое время узнать что такое многострочные строки, это очень удобные штуки

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String PASSWORD_LIST_FORMAT = "\n%s) Сайт: %s, Пароль: %s";
в одной строчке сразу несколько проблем:

1. Если значение константы начинается или заканчивается на спецсимвол, то этот символ должен быть вынесен из этой константы. Очевидно, что это часть форматированного сообщения, но сообщения должны быть цельные и единые, а форматирование - просто их объединяет. Пусть оно объединяет их в том месте, где оно их объединяет)) Надеюсь теперь стало очевидно почему не надо спецсимволы так использовать.
2. Вижу закрывающую скобку, но не вижу открывающуюся..... хотя может так оно и задумано. Но если вдруг это число, то почему тогда вы вставляете туда строку? Вставляйте число

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final int EDIT_COMMAND_LENGTH_HAS_DESCRIPTION = 5;
1. Константы относящиеся к команде должны быть определи вместе с командой
2. Если константа используется в одном единственном месте, то она должна быть определена именно в том классе, где она используется. В данном случае в EditHandler. И быть **приватной**. Инкапсуляцию вы видимо вообще не уважаете.

Эти же замечания относятся и к другим константам

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String DECRYPT_EXCEPTION = "Ошибка дешифрования пароля";
2 этих константы нигде не используются

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +public class Constants {
не надо устраивать свалку из констант. Как минимум они должны быть поделены по темам. И не надо в общую кучу выкидывать константы, которые нужны только в одном месте.

2024-11-27 19:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Response.java
> +public record Response(String message, State botState) {
Ребята, в чём дело? Почему возникают такие сложности, почему не получается соблюсти элементарные требования?

Пока не приведёте код в соответствие требованиям, дальше проверять не буду!

2024-11-27 19:37 UTC, vpyzhyanov commented
> Конфликты устранены, первая задача влита во вторую - теперь все изменения учитываются)

Почему-то "левые" изменения всё ещё остались. Например изменения pom файла.

что интересно, я попробовал влить main в task2 и получился 45 изменённых файлов.😳 Как так? Я ожидал, что не будет ни одного

2024-11-28 18:03 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Command.java
> +public class Command {
переделал в enum

2024-11-28 18:05 UTC, Waltans commented on pom.xml
> -    </scm>
Да, так и было, сейчас влили main

2024-11-28 18:06 UTC, Waltans commented
> Почему-то "левые" изменения всё ещё остались. Например изменения pom файла.
> 
> что интересно, я попробовал влить main в task2 и получился 45 изменённых файлов.😳 Как так? Я ожидал, что не будет ни одного

теперь при вливании main в master нет изменений

2024-11-28 18:15 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final Map<String, List<Integer>> commandsAndNumberOfParams = Map.of(
переделал на enum - теперь статиков нигде нет, требование соблюдается)
да, вы правы... подразумевалось, что это будут неизменяемые данные, куда статик вроде и подходит (но всё равно нарушает требования). хотя получили совсем обратное - сейчас увидели и осознали это (и публичность ещё добавила проблем)... ошибку поняли, всё исправлено

2024-11-28 18:17 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Command.java
> +    public static final Map<String, String> commandKeyMapping = Map.of(
переделал на enum - теперь все поля приватные, доступ через геттеры (соблюдается инкапсуляция), и все данные (команда как она есть, её подпись на клавиатуре и кол-во параметров) инкапсулируются в самих командах

2024-11-28 18:18 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String WELCOME_MESSAGE = "Здравствуйте. Я бот, который поможет Вам генерировать и управлять паролями.\n\n" +
да, сделал вместо \n многострочные строки

2024-11-28 18:20 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String PASSWORD_LIST_FORMAT = "\n%s) Сайт: %s, Пароль: %s";
1. про спецсимволы понятно. убрал его из константы, вынес туда, где из константы формируется непосредственно сообщение к ответу
2. скобка - это номер пароля в списке - например, "2)". сделал %d, чтобы вставлялось число

2024-11-28 18:26 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final int EDIT_COMMAND_LENGTH_HAS_DESCRIPTION = 5;
константы, которые используются только один раз, вынесены туда, где они используются, сделаны приватными.
Про первый пункт, правильно понял, что вы имели в виду константу COMMAND_WITHOUT_PARAMS_LENGTH? она используется много где в проекте, поэтому выглядит логичным (как нам кажется😅) оставить её в одном месте и обращаться из разных классов, хоть она и относится непосредственно к командам. пока оставил её вместе с константами, чтобы в каждом классе не определять одно и то же. будем рады обратной связи, чтобы понять, как лучше исправить замечание :)

2024-11-28 18:27 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final String DECRYPT_EXCEPTION = "Ошибка дешифрования пароля";
теперь их нет)

2024-11-28 18:27 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +public class Constants {
константы разделил по темам

2024-11-28 18:30 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Response.java
> +public record Response(String message, State botState) {
да, упущен момент с джавадоком... дописал его. тщательно проверили весь проект на наличие джавадоков и отсутствие статиков кроме констант -> код приведён в соответствие требованиям

2024-12-03 20:05 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final int EDIT_COMMAND_LENGTH_HAS_DESCRIPTION = 5;
> Про первый пункт, правильно понял, что вы имели в виду константу COMMAND_WITHOUT_PARAMS_LENGTH?

Замечания пишутся всегда на конкретную строчку кода. В данном случае на EDIT_COMMAND_LENGTH_HAS_DESCRIPTION. Но и для некоторых других констант это замечание справедливо. Надо использовать свой ум, чтобы понять к каким и исправить там тоже.

2024-12-03 20:07 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final int EDIT_COMMAND_LENGTH_HAS_DESCRIPTION = 5;
Вот пример

![image](https://github.com/user-attachments/assets/eff9df6b-2b87-4bec-b2eb-e66c9641913e)

Остальные тоже надо исправить

2024-12-03 20:09 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Constants.java
> +public class Constants {
>  используемые один раз - вынес и сделал приватными

С этим почему-то возникли проблемы. Ещё один пример:

![image](https://github.com/user-attachments/assets/02412d1f-597a-4fae-be91-12289b15360d)

2024-12-03 21:36 UTC, vpyzhyanov requested changes
слишком много тёмной стороны

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +        try{
зачем? Почему не используете форматирование? Я уже рассказывал как сделать это автоматически при коммите

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Response.java
> + * @param botState состояние бота после ответа
Ну вот и открылась тёмная сторона. Уже становится очевидно, что две логически не связанные друг с другом функциональности объединены в один класс. Непонятно зачем.

Вопрос для самоконтроля: каким образом "состояние бота" является часть ответа? Вы серьёзно его пользователю передаёте? Пользователь меняет состояние?

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +            List<KeyboardRow> keyboardRows = mainKeyboard();
И ведь действительно. Какое-то состояние передали и накрутили логику, который тут быть вообще не должно. **Добро пожаловать в коллективную безответственность**. В одночасье обесценили класс CommandService отжав у него часть работы.

Как правильно: Клавиатура должна определять в классе, отвечающем за логику. Про "состояния" вообще никто, коме самой логики, знать не должен. Класс Response должен передавать информацию по которой телеграмм бот сможет построит произвольную клавиатуру.

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> complexityKeyBoard() {
тут не место этому методу

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> sortKeyBoard() {
О_о вот это поворот. Если вы пытались ввести в заблуждение, то у вас это отлично получилось. Читаем название метода "Сортировать клавиатуру" (хотя на самом деле надо прочитать как "Сортировать ключ доски", т.е. keyboard - это одно слово).

Правильное название метода `createSelectSortTypeKeyboard`

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> listKeyBoard() {
похоже все методы так или иначе вводят в заблуждение, т.к. названы неправильно.

Запомните простое правило: метод **ВСЕГДА** **глагол!**

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/UserStateCache.java
> +package ru.naumen.bot;
опять заглянули на тёмную сторону. Какое отношение кеш имеет к боту? Не увидел ни одной связи с ботом

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/UserStateCache.java
> +            return new ArrayList<>();
привыкайте работать с неизменяемыми коллекциями. `List.of()`

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/ValidationService.java
> +        State state = userStateCache.getUserState(userId);
подозрение на коллективную безответственность. Сильно подозреваю, что класс userStateCache лишён инкапсуляции и очень зря ходит к кому попало.

Что мы имеем, "Сервис валидации введённых данных" для проверки корректности команды требует указать ID пользователя. То есть вы хотите сказать проверка команды зависит от того, кто её ввёл?! Это не может быть так. Я ещё могу понять, если ValidationService зависит от состояния (и то не очень понимаю), но от пользователя точно не должен зависеть.

Сильное подозрение, что ValidationService ворует часть работы у обработчиков команды. Всё-таки с состоянием обычно работают именно они и больше никто не должен работать с состоянием

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/ValidationService.java
> +        return complexity.equals("1") ||
для лёгкости чтения кода, логическое условие нужно писать в начале строки

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/ValidationService.java
> +    public boolean areNumbersEditCommandParams(String[] splitCommand) {
инкапсуляция вышла и не вернулась. Метод обязан быть private. А то, что тесты его используют меня совершенно не волнует.

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/ValidationService.java
> +    public boolean areNumbersDeleteCommandParams(String[] splitCommand) {
все методы ниже аналогично. Почему-то не дружите с инкапсуляцией

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/command/CommandFinder.java
> +    public Command findCommand(String input) throws CommandNotFoundException {
1. Слишком жирно создавать целый класс для такой простой задачи. CommandService сам в состоянии разобраться со своими командами, всё-таки это его задача вызвать нужную команду. Привет коллективной безотстветственности.
2. Линейная сложность? Не, так не пойдёт. Вы разве не изучали коллекции? Самое время использовать полученные знания

В общем класс надо удалить за ненадобностью. А если вы переживаете за ValidationService, то не нужно переживать, он вообще сомнительный персонаж. Вообще-то каждая команда сама себя провалидировать. И правила валидации у каждой из них могут быть **сильно разные**, нельзя их объединять в одну гребёнку.

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/ValidationService.java
> +public class ValidationService {
на всякий случай продублирую

> А если вы переживаете за ValidationService, то не нужно переживать, он вообще сомнительный персонаж. Вообще-то каждая команда сама себя провалидировать. И правила валидации у каждой из них могут быть **сильно разные**, нельзя их объединять в одну гребёнку.

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/CommandService.java
> +            return performNotCommandMessage(splitCommand, userId);
в этот раз у вас не получилось меня обмануть! Сначала вы ищете команду. Почему-то утверждаете, что её отсутствие - это некорректная ситуация (исключение бросается только в некорректной ситуации).

![image](https://github.com/user-attachments/assets/ec9e92dc-61ef-4bb1-8937-29aa24b00dcd)

А дальше как ни в чём не бывало продолжаете обработку.

В общем убираем исключение. Ситуация корректна. Метод findCommand должен возвращать Optional

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/command/CommandFinder.java
> +        throw new CommandNotFoundException("Команда не найдена: " + input);
дублирую

> убираем исключение. Ситуация корректна. Метод findCommand должен возвращать Optional

2024-12-03 21:36 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/command/Command.java
> +        this.validParamCounts = validParamCounts;
теперь я понял что не так. Вы попытались унифицировать неунифицируемые вещи. Такая попытка обречена на провал, а пострадает ООП.

2024-12-03 21:36 UTC, vpyzhyanov commented on src/test/java/ru/naumen/service/ValidationServiceTest.java
> +        Assertions.assertFalse(validationService.areNumbersDeleteCommandParams(splitCommand));
тестирование методов, которые вообще в проекте не используются

2024-12-04 17:06 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +        try{
Не за чем. Исправил

2024-12-04 17:27 UTC, Waltans commented on src/main/java/ru/naumen/service/ValidationService.java
> +    public boolean areNumbersEditCommandParams(String[] splitCommand) {
Убрал методы

2024-12-04 17:27 UTC, Waltans commented on src/main/java/ru/naumen/service/ValidationService.java
> +    public boolean areNumbersDeleteCommandParams(String[] splitCommand) {
убрал

2024-12-04 17:30 UTC, Waltans commented on src/main/java/ru/naumen/bot/UserStateCache.java
> +            return new ArrayList<>();
сделал

2024-12-04 17:31 UTC, Waltans commented on src/main/java/ru/naumen/bot/UserStateCache.java
> +package ru.naumen.bot;
перенес класс. Отношение к боту не имеет

2024-12-04 17:35 UTC, Waltans commented on src/main/java/ru/naumen/service/ValidationService.java
> +        return complexity.equals("1") ||
ок

2024-12-04 17:53 UTC, Waltans commented on src/main/java/ru/naumen/bot/command/CommandFinder.java
> +    public Command findCommand(String input) throws CommandNotFoundException {
Жирно, занесу логику в енам. Переделаю на мапу и получим константную сложность. Удалил класс

2024-12-04 19:08 UTC, Waltans commented on src/main/java/ru/naumen/service/ValidationService.java
> +public class ValidationService {
убрал validationSerivice

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/service/CommandService.java
> +            return performNotCommandMessage(splitCommand, userId);
Исправил ситуацию

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/command/CommandFinder.java
> +        throw new CommandNotFoundException("Команда не найдена: " + input);
Больше его нет

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/command/Command.java
> +        this.validParamCounts = validParamCounts;
Хм, наверное, так и есть

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/Response.java
> + * @param botState состояние бота после ответа
Наверное, это скорее не самый удачный javaDoc, тут скорее состояние пользователя после ответа бота, бот никакого отношения не имеет к состоянию ответа. Да, мы передаем состояние, только не пользователю, а боту для обработки. Пользователь меняет свое состояние.

Но справедливости ради, замечу, что состояние пользователя не обязательно передавать с ответом, мы всегда его можем узнать получив из кеша, поэтому в какой-то мере это избыточно, уберу это и переделаю обработку команд ботом

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> complexityKeyBoard() {
Вынес методы

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> sortKeyBoard() {
Исправил названия методов

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> listKeyBoard() {
Да, понятно

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/service/ValidationService.java
> +        State state = userStateCache.getUserState(userId);
Теперь этого класса нет

2024-12-06 05:34 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +            List<KeyboardRow> keyboardRows = mainKeyboard();
Теперь нет такой логики, комманд сервис решает какую клавиатуру показать пользователю

2024-12-06 05:35 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/command/Command.java
> +        this.validParamCounts = validParamCounts;
сделали валидацию в самих обработчиках

2024-12-06 05:39 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +    public static final int EDIT_COMMAND_LENGTH_HAS_DESCRIPTION = 5;
понял, всё исправлено) упустили момент что несколько usages могут быть в пределах одного класса😅

2024-12-06 05:39 UTC, totheskysx10 commented on src/main/java/ru/naumen/bot/Constants.java
> +public class Constants {
исправлено

2024-12-06 09:31 UTC, totheskysx10 commented on src/test/java/ru/naumen/service/ValidationServiceTest.java
> +        Assertions.assertFalse(validationService.areNumbersDeleteCommandParams(splitCommand));
удалены, как и сам validationService

2024-12-08 11:14 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/Response.java
> + * @param botState состояние бота после ответа
> его можем узнать получив из кеша, поэтому в какой-то мере это избыточно

Это не просто избыточно, это категорически неправильно. Но теперь стало правильно, теперь сама команда меняет состояние, обращаясь к соответствующему сервису. Так и должно было быть с самого начала. То есть смена состояния - это ответственность именно обработчика конкретной команды.

2024-12-08 11:20 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +            List<KeyboardRow> keyboardRows = mainKeyboard();
Ай яй яй, сделали страшное, затянули зависимость от телеграмма в commandService. Притом сделав это очень не очевидно. Прочувствуйте: метод отправки сообщения в чат обращается в какой-то сервис по **обработке** команд, чтобы получить клавиатуру. Тут возникает масса вопросов: 

1. как он узнает какую клавиатуру надо сейчас отобразить? 
2. То есть клавиатура вообще не связана с обработкой команды? Но это же не правда!

Самый правильный способ - добавить это в класс ответа. Вероятно потребуется создать свой класс клавиатуры.

2024-12-08 11:23 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> complexityKeyBoard() {
Стало чуть лучше, но исходный посыл замечания не исправлен. Связь с телеграммом как была, так и осталась.

2024-12-08 11:31 UTC, vpyzhyanov commented on src/main/java/ru/naumen/bot/command/CommandFinder.java
> +    public Command findCommand(String input) throws CommandNotFoundException {
Ну вот, другое дело!

2024-12-08 12:29 UTC, vpyzhyanov approved these changes
Как исправите последние замечания, можете мёрджить. Задача принята.

Оценка:

- ООП: 4 балла (снизил за то, что переметнулись на тёмную сторону, т.е. прокинули связь с телеграммом внутрь обработчика команд)
- GIT: 3 балла

2024-12-08 12:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/CommandService.java
> +    public List<KeyboardRow> getKeyboards(long userId) {
> Ай яй яй, сделали страшное, затянули зависимость от телеграмма в commandService. Притом сделав это очень не очевидно. Прочувствуйте: метод отправки сообщения в чат обращается в какой-то сервис по обработке команд, чтобы получить клавиатуру

2024-12-08 12:29 UTC, vpyzhyanov commented on src/main/java/ru/naumen/service/CommandService.java
> +import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.KeyboardRow;
вот тут очевидна лишняя зависимость

2024-12-08 15:09 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +            List<KeyboardRow> keyboardRows = mainKeyboard();
Добавл класс клавиатуры и в ответ добавил клавиатуру

2024-12-08 15:09 UTC, Waltans commented on src/main/java/ru/naumen/bot/TelegramBot.java
> +    private List<KeyboardRow> complexityKeyBoard() {
Убрал связь клавиатуры

2024-12-08 15:10 UTC, Waltans commented on src/main/java/ru/naumen/service/CommandService.java
> +    public List<KeyboardRow> getKeyboards(long userId) {
да, понятна ошибка

2024-12-08 15:10 UTC, Waltans commented on src/main/java/ru/naumen/service/CommandService.java
> +import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.KeyboardRow;
fix

2024-12-08 15:10 UTC, merged